---

# Virtualenv settings.
enable_deadsnakes_ppa: true
recreate_virtualenv: false
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/opt/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: playlistor


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  BROKER_URL: "{{ broker_url }}"
  REDIS_URL: "{{ redis_url }}"
  SPOTIFY_REDIRECT_URI: "{{ spotify_redirect_uri }}"
  SPOTIFY_CLIENT_ID: "{{ spotify_client_id }}"
  SPOTIFY_CLIENT_SECRET: "{{ spotify_client_secret }}"
  APPLE_KEY_ID: "{{ apple_key_id }}"
  APPLE_TEAM_ID: "{{ apple_team_id }}"
  SENTRY_DSN: "{{ sentry_dsn }}"
